### ISSUE TITLE
Decide on a standard license?

### ISSUE THREAD

**Issue by tkelman** [JuliaCon/talks2016#1]
I think CC-BY-SA or something similar was used the first year?

**Comment by JeffreySarnoff** [comment]
MIT Open Courseware is using 
CC BY-NC-SA version 4 (international)
Which says, roughly:
free to use with attribution for non-commercial purposes, if adapted [the original has been modified or altered] the work which contains that adaptation of the original material must also be distributed with the license CC BY-NC-SA.

**Comment by JeffreySarnoff** [comment]
A potential problem with CC's SA (share alike) licences [version 3, not sure if it got addressed in version 4] is that a repackager of unaltered material is free to impose any license terms -- any, to include "while this collection of advanced technology presentations is distributed to you without charge you must charge $500,000 for each copy and you are only allowed to distribute copies to representatives of North ___."

**Comment by JeffreySarnoff** [comment]
I prefer CC BY-NC version 4 international:
Give me credit for my own work, and you need a separate agreement before using my work commercially. And those two conditions apply to each recipient of any redistibution of the original material or modified versions of the material.
